import React,{useState,useEffect,useRef} from 'react';
import{createRoot}from'react-dom/client';import'./style.css';
type Turn={role:string,text:string,start_s:number|null,end_s:number|null};
type Review={label:string,include:boolean,note:string,reviewer:string,version:number};
type Candidate={id:string,conversation_id:string,turn_index:number,conversation:{id:string,split:string,provenance:string,timing_source:string,turns:Turn[]},detection:{user_onset_s:number,overlap_s:number,agent_turn_indices:number[]},review:Review|null,audio:{duration:number}|null};
type Metrics={conversations:number,candidates:number,reviewed:number,included:number,timed_user_turns:number,untimed_user_turns:number};
let token='';async function api<T>(path:string,body?:unknown):Promise<T>{const r=await fetch('/api/curation'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','x-repair-token':token},body:body===undefined?undefined:JSON.stringify(body)});if(!r.ok){const e=await r.json();throw new Error(typeof e.detail==='string'?e.detail:JSON.stringify(e.detail))}return r.json()}
function Timeline({c}:{c:Candidate}){const turns=c.conversation.turns;const max=Math.max(1,...turns.map(t=>t.end_s||0));return <svg className="timeline" viewBox="0 0 660 120" role="img" aria-label="Speech intervals: agent above, user below"><text x="0" y="31">Agent</text><text x="0" y="76">User</text>{turns.map((t,i)=>t.start_s===null?null:<rect key={i} className={i===c.turn_index?'target-span':t.role==='assistant'?'agent-span':'user-span'} x={70+t.start_s/max*570} y={t.role==='assistant'?15:60} width={Math.max(1,((t.end_s||0)-t.start_s)/max*570)} height="23" rx="3"><title>{t.role}: {t.start_s}–{t.end_s} s</title></rect>)}<text x="70" y="108">0 s</text><text x="580" y="108">{max.toFixed(1)} s</text></svg>}
function Detail({c,refresh}:{c:Candidate,refresh:()=>Promise<void>}){
 const [label,setLabel]=useState(c.review?.label||'uncertain'),[include,setInclude]=useState(c.review?.include||false),[note,setNote]=useState(c.review?.note||''),[reviewer,setReviewer]=useState(c.review?.reviewer||'local-reviewer'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const audio=useRef<HTMLAudioElement>(null);
 async function save(){setBusy(true);setMessage('');try{await api('/reviews/'+c.id,{label,include,note,reviewer,expected_version:c.review?.version||0});await refresh();setMessage('Review saved.')}catch(e){setMessage(String(e))}finally{setBusy(false)}}
 async function attach(file:File){setBusy(true);try{const r=await fetch(`/api/curation/conversations/${c.conversation_id}/audio`,{method:'POST',headers:{'Content-Type':'audio/wav','x-repair-token':token},body:file});if(!r.ok)throw new Error((await r.json()).detail);await refresh();setMessage('Source audio attached.')}catch(e){setMessage(String(e))}finally{setBusy(false)}}
 return <><div className="detail-heading"><div><div className="eyebrow">{c.conversation.split.toUpperCase()} / {c.conversation.timing_source.replaceAll('_',' ')}</div><h2>{c.conversation.id}</h2></div><span className="badge">{c.review?'reviewed':'candidate'}</span></div><div className="result"><strong>User starts during agent speech</strong><p>Onset {c.detection.user_onset_s.toFixed(3)} s · overlap {c.detection.overlap_s.toFixed(3)} s</p><Timeline c={c}/><small>Timing detects overlap. Intent and whether the agent yielded require review.</small></div>
 <div className="source">{c.conversation.provenance}</div>
 {c.audio?<div className="source-audio"><audio ref={audio} controls preload="metadata" src={`/api/curation/conversations/${c.conversation_id}/audio`}/><button className="secondary" onClick={()=>{if(audio.current){audio.current.currentTime=Math.max(0,c.detection.user_onset_s-2);void audio.current.play().catch(e=>setMessage(String(e)))}}}>Listen from 2 s before onset</button></div>:<div className="no-audio"><strong>No source audio attached.</strong><p>Timestamp-only review cannot independently verify audible interruption. Attach the original WAV to listen.</p><label className="file-label">Attach source WAV (≤50 MB, ≤15 min)<input type="file" accept=".wav" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void attach(f)}}/></label></div>}
 <h3>Conversation context</h3><div className="transcript-list">{c.conversation.turns.map((t,i)=><div key={i} className={'utterance '+(i===c.turn_index?'focus-turn':'')}><span>{t.role} · {t.start_s===null?'untimed':`${t.start_s.toFixed(2)}–${t.end_s?.toFixed(2)} s`}{i===c.turn_index?' · candidate onset':''}</span><p>{t.text}</p></div>)}</div>
 <div className="review-form"><h3>Your annotation</h3><label>Decision<select value={label} onChange={e=>{setLabel(e.target.value);if(e.target.value!=='interruption')setInclude(false)}}><option value="uncertain">Uncertain / insufficient evidence</option><option value="interruption">Confirmed interruption</option><option value="backchannel">Backchannel / acknowledgement</option><option value="other_overlap">Other overlap / timing issue</option></select></label><label>Reviewer<input value={reviewer} maxLength={80} onChange={e=>setReviewer(e.target.value)}/></label><label>Evidence or notes<textarea value={note} maxLength={2000} onChange={e=>setNote(e.target.value)} placeholder="What did you hear? Note timing uncertainty or annotation-only review."/></label><label className="check"><input type="checkbox" checked={include} disabled={label!=='interruption'} onChange={e=>setInclude(e.target.checked)}/> Include this confirmed interruption in exports</label><button disabled={busy||!reviewer.trim()} onClick={save}>Save review</button><p role="status">{message}</p></div></>;
}
function App(){const[items,setItems]=useState<Candidate[]>([]),[metrics,setMetrics]=useState<Metrics|null>(null),[selected,setSelected]=useState(''),[draft,setDraft]=useState(''),[showImport,setShowImport]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all'),[exportId,setExportId]=useState('');
 async function refresh(){const [c,m]=await Promise.all([api<{items:Candidate[],total:number}>('/candidates'),api<Metrics>('/metrics')]);setItems(c.items);setMetrics(m);setSelected(old=>old||c.items[0]?.id||'')}
 useEffect(()=>{api<{token:string}>('/bootstrap').then(async b=>{token=b.token;await refresh()}).catch(e=>setError(String(e)))},[]);
 async function ingest(text:string){setBusy(true);setError('');try{const r=await api<{imported:number,duplicates:number,candidates:number}>('/import',{jsonl:text});await refresh();setNotice(`${r.imported} conversations imported · ${r.candidates} overlap candidates · ${r.duplicates} duplicates skipped`);setShowImport(false);setDraft('')}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function demo(){const r=await fetch('/api/curation/example');await ingest(await r.text())}
 async function exp(){try{const r=await api<{id:string,records:number}>('/exports',{});setExportId(r.id);setNotice(`Created immutable export with ${r.records} reviewed examples. Audio is referenced, not copied.`)}catch(e){setError(String(e))}}
 const visible=items.filter(c=>filter==='all'||filter==='unreviewed'&&!c.review||filter==='included'&&c.review?.include);const c=items.find(x=>x.id===selected);
 return <div className="layout"><aside><a className="brand" href="/">↳ <span>Interruption<br/>Curation</span></a><div className="small-label">DATASET WORKSPACE</div><div className="nav-item">◉ &nbsp; Overlap candidates</div><div className="roadmap">01 Import timed conversations<br/>02 Inspect candidate overlaps<br/>03 Review and export</div><div className="local"><span className="dot"/>Local · no model required<br/><small>Goal 01 / interruptions</small></div></aside><main><header><div><div className="eyebrow">CURATION / TIMING FIRST</div><h1>Find where the user cuts in.</h1><p>Turn timestamped conversations into reviewed interruption examples.</p></div><button onClick={()=>setShowImport(!showImport)}>Import dataset</button></header><div className="notice"><strong>Overlap is a candidate, not a verdict.</strong><span>Laya, correction detection, and raw-audio speaker detection are not used in this first pass.</span></div>
 {error&&<div role="alert" className="error">{error}<button className="secondary" onClick={()=>setError('')}>Dismiss</button></div>}{notice&&<p role="status" className="import-status">{notice}</p>}
 {showImport&&<section className="import-panel"><h2>Import conversational JSONL</h2><p>One conversation per line: id, source_group, split, provenance, timing_source, and turns with role, text, start_s, end_s. Times are seconds on the same source-audio clock. Speaker roles must be known.</p><input aria-label="Choose JSONL dataset" type="file" accept=".jsonl,.ndjson,.txt" onChange={e=>{const f=e.target.files?.[0];if(f){if(f.size>2_000_000)setError('JSONL must be under 2 MB');else void f.text().then(setDraft)}}}/><textarea aria-label="JSONL conversations" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Paste JSONL or choose a file"/><button disabled={busy||!draft.trim()} onClick={()=>ingest(draft)}>Import and detect</button><a href="/api/curation/example">Download format example</a></section>}
 <div className="stats">{[['Conversations',metrics?.conversations||0],['Overlap candidates',metrics?.candidates||0],['Reviewed',metrics?.reviewed||0],['Included',metrics?.included||0]].map(([name,value])=><div key={name}><small>{name}</small><strong>{value}</strong></div>)}</div><div className="coverage">{metrics?.timed_user_turns||0} timed user turns searched · {metrics?.untimed_user_turns||0} untimed user turns not searched. No recall claim.</div>
 <div className="workspace"><section className="run-list"><div className="queue-head"><h2>Review queue</h2><select aria-label="Filter candidates" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All</option><option value="unreviewed">Unreviewed</option><option value="included">Included</option></select></div>{visible.map(x=><button key={x.id} className={'run-card '+(selected===x.id?'chosen':'')} onClick={()=>setSelected(x.id)}><strong>{x.conversation.id}</strong><span>{x.detection.user_onset_s.toFixed(2)} s · {x.detection.overlap_s.toFixed(2)} s overlap</span><span className="badge">{x.review?.label||'unreviewed'}</span></button>)}{!items.length&&<div className="empty"><p>Import timestamps to find overlap candidates.</p><button className="secondary" disabled={busy} onClick={demo}>Load constructed demo</button><p>Three fictional conversations, no audio or gold labels.</p></div>}<div className="export-panel"><button className="secondary" disabled={!metrics?.included} onClick={exp}>Export reviewed examples</button>{exportId&&<a href={'/api/curation/exports/'+exportId}>Download JSONL</a>}<small>Latest review decisions only. Source context and audio references retained.</small></div></section><section className="detail">{c?<Detail key={c.id+':'+(c.review?.version||0)+':'+!!c.audio} c={c} refresh={refresh}/>:<div className="welcome"><span>FIRST CURATION GOAL</span><h2>Did the user interrupt the agent?</h2><p>We find the temporal event first. You determine whether it was an interruption, a backchannel, or uncertain.</p><p>Conversations without timestamps are retained but not searched. Unlabelled mixed audio requires a separate speaker-detection step that is not implemented here.</p></div>}</section></div></main></div>}
createRoot(document.getElementById('root')!).render(<App/>);
